name: mikan_flutter
description: mikanani.me

version: 1.0.0-RC27+49

publish_to: none

environment:
  sdk: ">=2.16.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.14.1
  firebase_analytics: ^9.1.5
  firebase_crashlytics: ^2.6.2
  path_provider: ^2.0.9
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  dio_http2_adapter: ^2.0.0
  html: ^0.15.0
  provider: ^6.0.2
  oktoast: ^3.1.4
  pull_to_refresh: ^2.0.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  palette_generator: ^0.3.3
  flutter_spinkit: ^5.1.0
  fluentui_system_icons: ^1.1.165
  clipboard: ^0.1.3
  url_launcher: ^6.0.20
  share_plus: ^4.0.4
  flutter_widget_from_html: ^0.8.5
  extended_sliver: ^2.0.1
  extended_image: ^6.0.2+1
  waterfall_flow: ^3.0.2
  modal_bottom_sheet: ^2.0.1
  jiffy: ^5.0.0
  android_intent_plus: ^3.1.1
  isolate: ^2.1.1
  connectivity_plus: ^2.3.0
  ff_annotation_route_core: ^2.0.4
  ff_annotation_route_library: ^3.0.0
  sprung: ^3.0.0
  sliver_tools: ^0.2.5
  bitsdojo_window: ^0.1.1+1
  flutter_displaymode: ^0.4.0
  infinite_carousel: ^1.0.2
  flex_color_picker: ^2.4.0


dependency_overrides:
  wakelock: ^0.6.1+1

dev_dependencies:
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
  hive_generator: ^1.1.2
  flutter_launcher_icons: ^0.9.2
  yaml: ^3.1.0
  flutter_lints: ^1.0.4
#  derry: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/mikan.png"


## pub global activate derry
## derry upgrade
#scripts:
#  # derry build
#  build:
#    - flutter pub run build_runner build --delete-conflicting-outputs
#  # derry watch_build
#  watch_build:
#    - flutter pub run build_runner watch --delete-conflicting-outputs
#  # derry ff_route_first
#  ff_route_first:
#    - flutter pub global activate ff_annotation_route
#    - ff_route -s --route-constants --route-helper --route-names --no-is-initial-route --supper-arguments
#  # derry ff_route
#  ff_route: ff_route


